version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: website-checker
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - 8000:8000
    volumes:
      - ./src:/src
    entrypoint:
      tail
      -f
      /dev/null
