site_name: Website Checker

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Website Checker Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
